  0  1  3  0  1 20  0.0  0.97  5  -1  -1
  1  2  3        No delay layer beds
         0  10.00000(10e12.4)                   -1     PRECONSOLIDATION HEAD Layer   1
         06.0000e-05(10e12.4)                   -1     ELASTIC STORAGE Layer   1
         06.0000e-04(10e12.4)                   -1     INELASTIC STORAGE Layer   1
         00.0000e+00(10e12.4)                   -1     CONSOLIDATION Layer   1
         0  10.00000(10e12.4)                   -1     PRECONSOLIDATION HEAD Layer   2
         06.0000e-05(10e12.4)                   -1     ELASTIC STORAGE Layer   2
         06.0000e-04(10e12.4)                   -1     INELASTIC STORAGE Layer   2
         00.0000e+00(10e12.4)                   -1     CONSOLIDATION Layer   2
         0  10.00000(10e12.4)                   -1     PRECONSOLIDATION HEAD Layer   3
         06.0000e-05(10e12.4)                   -1     ELASTIC STORAGE Layer   3
         06.0000e-04(10e12.4)                   -1     INELASTIC STORAGE Layer   3
         00.0000e+00(10e12.4)                   -1     CONSOLIDATION Layer   3
 0 150 0 151 0 152 0 153 0 154 0 155
 1  1  5  5  1  0  1  0  1  0  1  0  0  0  0  0  0		 
