      MODULE GWFDPFMODULE
        INTEGER,SAVE,POINTER::IDPFCB,IDPFHD,IDPFDD
        INTEGER, SAVE, ALLOCATABLE, DIMENSION (:) :: IBOUNDIM
        REAL, SAVE, ALLOCATABLE, DIMENSION(:) ::SC1IM,SC2IM,PHIF,DDFTR
        REAL, SAVE,ALLOCATABLE,DIMENSION(:)::alphaIM,betaIM,srIM,
     1        brookIM,BPIM
C
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: HNEWIM,HOLDIM
        DOUBLE PRECISION, SAVE,DIMENSION(:), POINTER :: SNIM,SOIM
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: DIADDF,RDDF
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: OFFDDFM
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: OFFDDFIM
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: AKRCIM
        DOUBLE PRECISION, SAVE,ALLOCATABLE,DIMENSION(:) :: CBCFIM
      END MODULE GWFDPFMODULE
C